# Преподаватель
# Access Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiI3ZjdlZmE1Yi0wYzY0LTQzNDMtOTU3Yy02YjUyZTBhNDQ2OTAiLCJQZXJzb25HdWlkIjoiNTEyNTBhOWItOGU2Mi00ZDQ0LTk2M2YtNjg4YjhmMGNkZWMzIiwiQ2hhaXJHdWlkIjoiIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAxIiwibmJmIjoxNzI0MzEyNjE5LCJleHAiOjE3MjY5MDQ2MTksImlhdCI6MTcyNDMxMjYxOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.pMs8EwNtfCyamXsdW0yI9I02p0WfZwz5oL6IyoVCd8M
# roles: [2]
# semesterId: 20

# Кафедра
# Access token
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiI2Y2U2NjEyMS1jMzhhLTRhYTUtYjVhYi01N2NmZDhiYTc0MTQiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiYzE5YmQ0ZTMtZDk2ZS00ZGQyLWJmMjgtNDQ2OWQzNjEwMTAyIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAzIiwibmJmIjoxNzI0MzExMzkzLCJleHAiOjE3MjY5MDMzOTMsImlhdCI6MTcyNDMxMTM5MywiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.J7M8usfdGoQxo_BDretgXJZxAgRBpR29E0bExktDlio
# roles: [3]
# semesterId: 20

# Кафедра
# Access token
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiJjYThhZDE4YS0yM2Y1LTRmZjQtYWVhZi1mZjdjMmE2MmJlZmQiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiIiwiRmFjdWx0eUd1aWQiOiJhOTFhZDNhNC01MGNiLTQwNGUtOWI1NS0zOTIyOTQ4YTliNDciLCJVc2VybmFtZSI6ImF0dGVzdDA0IiwibmJmIjoxNzI0NDAzMDA5LCJleHAiOjE3MjY5OTUwMDksImlhdCI6MTcyNDQwMzAwOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.R32TSU1oldsXGkdvRONrNppbQSMPbonKQg7g_WcrBic
# roles: [1]
# semesterId: 20

### Авторизация
POST https://localhost:44434/Account/Login?loginPair=attest04%3Ah9n8YDC2

### Список факультетов
GET https://localhost:44434/Faculty/Faculties
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiJmMzkyYTA2NC0wZTI0LTRjM2MtOGEzOC1iNmE1YjllMTcyM2EiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiYzE5YmQ0ZTMtZDk2ZS00ZGQyLWJmMjgtNDQ2OWQzNjEwMTAyIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAzIiwibmJmIjoxNzI0MzExMTg3LCJleHAiOjE3MjY5MDMxODcsImlhdCI6MTcyNDMxMTE4NywiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.mB9KPc8fN2uFux7HVaW-0NZPE800pLH4BBSp2sEh4ro

### Список курсов
GET https://localhost:44434/Journal/GetBindings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiI3ZjdlZmE1Yi0wYzY0LTQzNDMtOTU3Yy02YjUyZTBhNDQ2OTAiLCJQZXJzb25HdWlkIjoiNTEyNTBhOWItOGU2Mi00ZDQ0LTk2M2YtNjg4YjhmMGNkZWMzIiwiQ2hhaXJHdWlkIjoiIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAxIiwibmJmIjoxNzI0MzEyNjE5LCJleHAiOjE3MjY5MDQ2MTksImlhdCI6MTcyNDMxMjYxOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.pMs8EwNtfCyamXsdW0yI9I02p0WfZwz5oL6IyoVCd8M
semesterid: 20

### Редактирование дисциплины
GET https://localhost:44434/Chair/SubGroupsByDisciplineBinding?courseId=799&disciplineId=1503
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiI2Y2U2NjEyMS1jMzhhLTRhYTUtYjVhYi01N2NmZDhiYTc0MTQiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiYzE5YmQ0ZTMtZDk2ZS00ZGQyLWJmMjgtNDQ2OWQzNjEwMTAyIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAzIiwibmJmIjoxNzI0MzExMzkzLCJleHAiOjE3MjY5MDMzOTMsImlhdCI6MTcyNDMxMTM5MywiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.J7M8usfdGoQxo_BDretgXJZxAgRBpR29E0bExktDlio
semesterid: 20

### Кураторы групп
GET https://localhost:44434/Chair/GetCurators
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiI2Y2U2NjEyMS1jMzhhLTRhYTUtYjVhYi01N2NmZDhiYTc0MTQiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiYzE5YmQ0ZTMtZDk2ZS00ZGQyLWJmMjgtNDQ2OWQzNjEwMTAyIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAzIiwibmJmIjoxNzI0MzExMzkzLCJleHAiOjE3MjY5MDMzOTMsImlhdCI6MTcyNDMxMTM5MywiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.J7M8usfdGoQxo_BDretgXJZxAgRBpR29E0bExktDlio

### Список кафедр
GET https://localhost:44434/Chair/ListAllChairs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiI2Y2U2NjEyMS1jMzhhLTRhYTUtYjVhYi01N2NmZDhiYTc0MTQiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiYzE5YmQ0ZTMtZDk2ZS00ZGQyLWJmMjgtNDQ2OWQzNjEwMTAyIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAzIiwibmJmIjoxNzI0MzExMzkzLCJleHAiOjE3MjY5MDMzOTMsImlhdCI6MTcyNDMxMTM5MywiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.J7M8usfdGoQxo_BDretgXJZxAgRBpR29E0bExktDlio

### Данные пользователя
GET https://localhost:44434/User/UserDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiI2Y2U2NjEyMS1jMzhhLTRhYTUtYjVhYi01N2NmZDhiYTc0MTQiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiYzE5YmQ0ZTMtZDk2ZS00ZGQyLWJmMjgtNDQ2OWQzNjEwMTAyIiwiRmFjdWx0eUd1aWQiOiIiLCJVc2VybmFtZSI6ImF0dGVzdDAzIiwibmJmIjoxNzI0MzExMzkzLCJleHAiOjE3MjY5MDMzOTMsImlhdCI6MTcyNDMxMTM5MywiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.J7M8usfdGoQxo_BDretgXJZxAgRBpR29E0bExktDlio

### Список учётных записей
GET https://localhost:44434/Employee/ListEmployees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiJjYThhZDE4YS0yM2Y1LTRmZjQtYWVhZi1mZjdjMmE2MmJlZmQiLCJQZXJzb25HdWlkIjoiIiwiQ2hhaXJHdWlkIjoiIiwiRmFjdWx0eUd1aWQiOiJhOTFhZDNhNC01MGNiLTQwNGUtOWI1NS0zOTIyOTQ4YTliNDciLCJVc2VybmFtZSI6ImF0dGVzdDA0IiwibmJmIjoxNzI0NDAzMDA5LCJleHAiOjE3MjY5OTUwMDksImlhdCI6MTcyNDQwMzAwOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmt1YnNhdS5ydSIsImF1ZCI6Imh0dHBzOi8vbmV3LWF0dC5rdWJzYXUucnUvIn0.R32TSU1oldsXGkdvRONrNppbQSMPbonKQg7g_WcrBic